version: '3'

services:
  app:
    container_name: ngx-material-upload
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: basic
    network_mode: host
    ports:
      - "6006:6006"
      - "4200:4200"
    volumes:
      - .:/workspaces:cached
