version: '3'

services:
  app:
    container_name: ngx-material-upload
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: basic
    network_mode: host
    volumes:
      - .:/workspaces:cached
